d04/d04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ex00/', include('ex00.urls'))
]

d04/ex00/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ex00

urlpatterns = [
    path('', ex00),
]

d04/ex01/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import django_view, display_view, templates_view

app_name = "ex01"
urlpatterns = [
    path('django/', django_view, name="django"),
    path('display/', display_view, name="display"),
    path('templates/', templates_view, name="templates")
]

d04/ex02/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import form_view, history

urlpatterns = [
    path('', form_view, name="input_data"),
    path('history/', history)
]

d04/ex03/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import table

urlpatterns = [
    path('', table)
]

d04/ex02/forms.py
from django import forms

class DataForm(forms.Form):
    input_data = forms.CharField()

d04/ex00/views.py
from django.shortcuts import render

# Create your views here.

def ex00(request):
    return render(request, "ex00/index.html")

d04/ex01/views.py
from django.shortcuts import render

# Create your views here.
def django_view(request):
    return render(request, "ex01/django.html")


def display_view(request):
    return render(request, "ex01/display.html")


def templates_view(request):
    return render(request, "ex01/templates.html")

d04/ex02/views.py
from django.shortcuts import render, redirect
from .forms import DataForm
from django.conf import settings
from datetime import datetime

def get_history():
    history = ""
    with open(settings.LOG_ROOT, "r") as f:
        history = f.read()
    history_lines = history.split("\n")
    return history_lines


def form_view(request):
    if request.method == "POST":
        form = DataForm(request.POST)
        if form.is_valid():
            with open(settings.LOG_ROOT, "a") as f:
                f.write(f"""{datetime.now()}: {form.cleaned_data.get("input_data")}\n""")
            return redirect("/ex02/")
    else:
        form = DataForm()
        history_lines = get_history()
    return render(request, "ex02/input_data.html", context={"form": form, "history_lines": history_lines})

def history(request):
    history_lines = get_history()
    return render(request, "ex02/history_page.html", context={"history_lines": history_lines})

d04/ex03/views.py
from django.shortcuts import render

# Create your views here.
def table(request):
    return render(request, "ex03/table.html", context={"colors": [i for i in range(255)]})

d04/ex00/templates/ex00/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ex00: Markdown Cheatsheet.</title>
</head>
<body>
  <h1>Markdown Cheatsheet.</h1>
  <h2>Headers</h2>
  <p># H1<br>
    ## H2<br>
    ### H3<br>
    #### H4<br>
    ##### H5<br>
    ###### H6</p>
  <h2>Emphasis</h2>
  <p>Emphasis, aka italics, with *asterisks* or _underscores_.<br>
    Strong emphasis, aka bold, with **asterisks** or __underscores__.<br>
    Combined emphasis with **asterisks and _underscores_**.<br>
    Strikethrough uses two tildes. ~~Scratch this.~~</p>
  <h2>Lists</h2>
  <p>
    1. First ordered list item<br>
    2. Another item<br>
    ⋅⋅* Unordered sub-list. <br>
    1. Actual numbers don't matter, just that it's a number<br>
    ⋅⋅1. Ordered sub-list<br>
    4. And another item.<br><br>
    ⋅⋅⋅You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).<br><br>
    ⋅⋅⋅To have a line break without a paragraph, you will need to use two trailing spaces.⋅⋅<br>
    ⋅⋅⋅Note that this line is separate, but within the same paragraph.⋅⋅<br>
    ⋅⋅⋅(This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)<br><br>
    * Unordered list can use asterisks<br>
    - Or minuses<br>
    + Or pluse
  </p>
  <h2>Links</h2>
  <p>
    [I'm an inline-style link](https://www.google.com)<br><br>
    [I'm an inline-style link with title](https://www.google.com "Google's Homepage")<br><br>
    [I'm a reference-style link][Arbitrary case-insensitive reference text]<br><br>
    [I'm a relative reference to a repository file](../blob/master/LICENSE)<br><br>
    [You can use numbers for reference-style link definitions][1]<br><br>
    Or leave it empty and use the [link text itself].<br><br>
    URLs and URLs in angle brackets will automatically get turned into links.<br>
    http://www.example.com or <http://www.example.com> and sometimes <br>
    example.com (but not on Github, for example).<br><br>
    Some text to show that the reference links can follow later.<br><br>
    [arbitrary case-insensitive reference text]: https://www.mozilla.org<br>
    [1]: http://slashdot.org<br>
    [link text itself]: http://www.reddit.com
  </p>
  <h2>Images</h2>
  <p>Here's our logo (hover to see the title text):<br><br>
    Inline-style: <br>
    ![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")<br><br>
    Reference-style: <br>
    ![alt text][logo]<br><br>
    [logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"
  </p>
  <h2>Code and Syntax Highlighting</h2>
  <p>
    ```javascript<br>
    var s = "JavaScript syntax highlighting";<br>
    alert(s);<br>
    ```<br><br>
    ```python<br>
    s = "Python syntax highlighting"<br>
    print s<br>
    ```<br><br>
    ```<br>
    No language indicated, so no syntax highlighting. <br>
    But let's throw in a <b>tag</b>.<br>
    ```
  </p>
  <h2>Tables</h2>
  <p>
    Colons can be used to align columns.<br><br>
    | Tables&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|&nbspAre&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|&nbspCool&nbsp&nbsp|<br>
    | ------------- |:-------------:|&nbsp-----:|<br>
    | col 3 is&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|&nbspright-aligned&nbsp|&nbsp$1600&nbsp|<br>
    | col 2 is&nbsp&nbsp&nbsp&nbsp&nbsp|&nbspcentered&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp$12&nbsp|<br>
    | zebra stripes&nbsp| are neat&nbsp&nbsp&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp&nbsp$1 |<br><br>
    There must be at least 3 dashes separating each header cell.<br>
    The outer pipes (|) are optional, and you don't need to make the <br>
    raw Markdown line up prettily. You can also use inline Markdown.v<br>
    Markdown | Less | Pretty<br>
    --- | --- | ---<br>
    *Still* | `renders` | **nicely**<br>
    1 | 2 | 3
  </p>
  <h2>Line Breaks</h2>
  <p>
    Here's a line for us to start with.<br><br>
    This line is separated from the one above by two newlines, so it will be a *separate paragraph*.<br><br>
    This line is also a separate paragraph, but...<br>
    This line is only separated by a single newline, so it's a separate line in the *same paragraph*.</p>
  <h2>YouTube Videos</h2>
  <p>
    [![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](http://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)
  </p>
</body>
</html>

d04/ex01/templates/ex01/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ex01/css/nav.css' %}">
    {% block style %}<link rel="stylesheet" href="{% static 'ex01/css/style1.css' %}">{% endblock %}
    <title>Ex01: {% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'ex01/nav.html' %}
    {% block content %}{% endblock %}
</body>
</html>

d04/ex01/templates/ex01/display.html
{% extends "ex01/base.html" %}
{% block title %}Display process of a static page.{% endblock %}
{% block content %}
  <h1>Display process of a static page.</h1>
  <p>
    In computer science, request–response or request–reply is one of the basic methods computers use to communicate with <br>
    each other in a network, in which the first computer sends a request for some data and the second responds to the request. <br>
    More specifically, it is a message exchange pattern in which a requestor sends a request message to a replier system, which <br>
    receives and processes the request, ultimately returning a message in response. It is analogous to a telephone call, in which<br>
    the caller must wait for the recipient to pick up before anything can be discussed. This is a simple but powerful messaging pattern<br>
    which allows two applications to have a two-way conversation with one another over a channel; it is especially <br>
    common in client–server architectures<br>
    <br>
    For simplicity, this pattern is typically implemented in a purely synchronous fashion, as in web service calls over HTTP, which holds <br>
    a connection open and waits until the response is delivered or the timeout period expires. However, request–response may also be <br>
    implemented asynchronously, with a response being returned at some unknown later time. When a synchronous system communicates with <br>
    an asynchronous system, it is referred to as "sync over async" or "sync/async".[2] This is common in enterprise application integration <br>
    (EAI) implementations where slow aggregations, time-intensive functions, or human workflow must be performed before a <br>
    response can be constructed and delivered.<br>
    <br>
    In contrast, one-way computer communication, which is like the push-to-talk or "barge in" feature found on some phones and two-way <br>
    radios, sends a message without waiting for a response. Sending an email is an example of one-way communication, and another example <br>
    are fieldbus sensors, such as most CAN bus sensors, which periodically and autonomously send out their data, whether or not any other <br>
    devices on the bus are listening for it. (Most of these systems use a "listen before talk" or other contention-based protocol <br>
    so multiple sensors can transmit periodic updates without any pre-coordination.)
  </p>
{% endblock %}

d04/ex01/templates/ex01/django.html
{% extends "ex01/base.html" %}
{% block title %}Django, framework web{% endblock %}
{% block content %}
	<h1>Django history</h1>
	<p>
		Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers,<br>
		it takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.
	</p>
	<p>
		Ridiculously fast.<br>
		Django was designed to help developers take applications from concept to completion as quickly as possible.</p>
	<p>
		Reassuringly secure.<br>
		Django takes security seriously and helps developers avoid many common security mistakes.
	</p>
	<p>
		Exceedingly scalable.<br>
		Some of the busiest sites on the web leverage Django’s ability to quickly and flexibly scale
	</p>
{% endblock %}

d04/ex01/templates/ex01/nav.html
{% block nav %}
<ul class="nav">
    <li>
        <a href="{% url 'ex01:django' %}">Django</a>
    </li>
    <li>
        <a href="{% url 'ex01:display' %}">Display</a>
    </li>
    <li>
        <a href="{% url 'ex01:templates' %}">Templates</a>
    </li>
</ul>
{% endblock %}

d04/ex01/templates/ex01/templates.html
{% extends "ex01/base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'ex01/css/style2.css' %}">{% endblock %}
{% block title %}Template engine.{% endblock %}
{% block content %}
  <h1>Template engine.</h1>
  <p>
    Being a web framework, Django needs a convenient way to generate HTML dynamically. The most common approach relies on templates.<br>
    A template contains the static parts of the desired HTML output as well as some special syntax describing how dynamic content will<br>
    be inserted. For a hands-on example of creating HTML pages with templates, see Tutorial 3.<br>
    <br>
    A Django project can be configured with one or several template engines (or even zero if you don’t use templates).<br>
    Django ships built-in backends for its own template system, creatively called the Django template language (DTL), <br>
    and for the popular alternative Jinja2. Backends for other template languages may be available from third-parties. <br>
    You can also write your own custom backend, see Custom template backend<br>
    <br>
    Django defines a standard API for loading and rendering templates regardless of the backend. Loading consists of <br>
    finding the template for a given identifier and preprocessing it, usually compiling it to an in-memory representation. <br>
    Rendering means interpolating the template with context data and returning the resulting string.<br>
    <br>
    The Django template language is Django’s own template system. Until Django 1.8 it was the only built-in option available.<br>
    It’s a good template library even though it’s fairly opinionated and sports a few idiosyncrasies. If you don’t have a<br>
    pressing reason to choose another backend, you should use the DTL, especially if you’re writing a pluggable application <br>
    and you intend to distribute templates. Django’s contrib apps that include templates, like django.contrib.admin, use the DTL.<br>
    <br>
    For historical reasons, both the generic support for template engines and the implementation of the Django template <br>
    language live in the django.template namespace
  </p>
{% endblock %}

d04/ex02/templates/ex02/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

d04/ex02/templates/ex02/history.html
<p>
  {% for line in history_lines %}
    {{ line }}<br>
  {% endfor %}
</p>

d04/ex02/templates/ex02/history_page.html
{% extends "ex02/base.html" %}
{% block title %}History{% endblock %}
{% block content %}
{% include "ex02/history.html" %}
{% endblock %}

d04/ex02/templates/ex02/input_data.html
{% extends "ex02/base.html" %}
{% block title %}History{% endblock %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit">
	</form>
	{% include "ex02/history.html" %}
{% endblock %}

d04/ex03/templates/ex03/table.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Table</title>
</head>
<body>
  <table>
    <tr>
      <th>BLACK</th>
      <th>RED</th>
      <th>GREEN</th>
      <th>BLUE</th>
    </tr>
    {% for color in colors %}
      <tr>
        <td style = "background-color : rgb({{ color }}, {{ color }}, {{ color }});">black</td>
        <td style = "background-color : rgb({{ color }}, 0, 0);">red</td>
        <td style = "background-color : rgb(0, {{ color }}, 0);">green</td>
        <td style = "background-color : rgb(0, 0, {{ color }});">blue</td>
      </tr>
    {% endfor %}
  </table>
</body>
</html>